version: 2.1
orbs:
  heroku: circleci/heroku@1.2.2
jobs:
  test:
    docker:
      - image: openjdk:11
    steps:
      - checkout
      - run:
          name: Test
          command: bash ./gradlew test

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only:
                - master
