package ai.salesfox.integration.scribeless.enumeration;

public enum ScribelessHandwritingStyles {
    //    ABRAHIM,
//    BRADY,
//    CHAPLIN,
//    DICKINSON,
//    EASLEY,
//    EMERSON,
//    ERNEST,
    FOSTER,
    //    FREUD,
    GEORGE,
    //    GINSBERG,
//    KUNJAR,
//    LYTLE,
//    MABUS,
//    MARK,
    NIGHTINGALE,
    //    PARKER,
//    PEYTON,
//    PLATH,
//    ROBINSON,
//    SAWDON,
//    SELLERS,
//    SIMON,
    STAFFORD,
    //    SUTTON,
//    THOMAS,
    TREMBLAY,
//    USTHER,
//    VIRGINIA,
//    WHITMAN,
//    WILLIAM,
//    WILLIAMS

}
